#!/bin/env bash
set -euo pipefail

AUTO_REBOOT_HOURS=8
BLUETOOTH_AUTO_SHUTOFF_MINUTES=5

# Download latest APK of Tor Browser
if [ ! -f /tmp/torbrowser.apk ]; then
	echo "Downloading Tor Browser APK..."
	TOR_BROWSER_VERSION="$(curl -s https://aus1.torproject.org/torbrowser/update_3/release/download-android-aarch64.json | jq -r '.version')"
	curl -s -o /tmp/torbrowser.apk https://dist.torproject.org/torbrowser/"$TOR_BROWSER_VERSION"/tor-browser-android-aarch64-"$TOR_BROWSER_VERSION".apk
fi

# Download latest APK of Signal
if [ ! -f /tmp/signal.apk ]; then
	echo "Downloading Signal APK..."
	curl -s https://api.github.com/repos/signalapp/Signal-Android/releases/latest | jq -r '.assets.[0].browser_download_url' | xargs -n 1 curl -s -o /tmp/signal.apk -L
fi

# Download latest APK of Neo Store
if [ ! -f /tmp/neostore.apk ]; then
	echo "Downloading Neo Store APK..."
	curl -s https://api.github.com/repos/NeoApplications/Neo-Store/releases/latest | jq -r '.assets.[0].browser_download_url' | xargs -n 1 curl -s -o /tmp/neostore.apk -L
fi

# Download latest APK of Futo Keyboard
if [ ! -f /tmp/futo.apk ]; then
	echo "Downloading Futo Keyboard APK..."
	curl -s https://api.github.com/repos/futo-org/android-keyboard/releases/latest | jq -r '.assets.[0].browser_download_url' | xargs -n 1 curl -s -o /tmp/futo.apk -L
fi

adb start-server
adb devices

adb install -g -i "com.machiav3lli.fdroid" /tmp/neostore.apk
echo "Installed Neo Store"
adb install -i "com.machiav3lli.fdroid" /tmp/signal.apk
echo "Installed Signal."
adb install -i "com.machiav3lli.fdroid" /tmp/futo.apk
echo "Installed Futo Keyboard"
adb install -i "com.machiav3lli.fdroid" /tmp/torbrowser.apk
echo "Installed Tor Browser"

adb shell settings put system status_bar_show_battery_percent 1
echo "Turned on battery percentage in status bar."

adb shell settings put global settings_reboot_after_timeout "$((AUTO_REBOOT_HOURS*3600000))"
echo "Auto-reboot timer set to $AUTO_REBOOT_HOURS hours."

adb shell settings put global bluetooth_off_timeout "$((BLUETOOTH_AUTO_SHUTOFF_MINUTES*60000))"
echo "Bluetooth auto-shutoff timer set to $BLUETOOTH_AUTO_SHUTOFF_MINUTES minutes."

adb shell settings put global network_location 2
echo "Network location provider set to GrapheneOS Proxy."

adb shell settings put global geocoder 2
echo "Geocoder set to GrapheneOS Proxy."

# Disable developer settings and ADB after setup is complete
adb shell settings put global development_settings_enabled 0
adb shell settings put global adb_enabled 0 || true
